### ISSUE TITLE
update earthengine python api fork ? 

### ISSUE THREAD

**Issue by 12rambau** [openforis/sepal#196]
**Describe the bug**
We are using a custom fork of earthengine in SEPAL (0.270) and the curent version have changed a bit. 
I start to face deprecation notice and more problematic, I'm not able to use some of the documenation examples any more. 

**To Reproduce**
```python

import ee 

help(ee.Authenticate)

>>>Help on function Authenticate in module ee:
>>>Authenticate(authorization_code=None, quiet=None, code_verifier=None)
>>>Prompts the user to authorize access to Earth Engine via OAuth2.
>>>
>>>Args:
>>>authorization_code: An optional authorization code.
>>>quiet: If true, do not require interactive prompts.
>>>code_verifier: PKCE verifier to prevent auth code stealing.
```

**Expected behavior**
According to the [documentation](https://developers.google.com/earth-engine/apidocs/ee-authenticate) there is now 4th parameter: `auth_mode` that is essential to connect to using the gcloud auth.

**Comment by 12rambau** [comment]
@dfguerrerom I tried to run `earthengine authenticate` from my SEPAL terminal and I got the following error : 

```
Traceback (most recent call last):
  File "/usr/local/bin/earthengine", line 5, in <module>
    from ee.cli.eecli import main
  File "/usr/local/lib/python3.8/dist-packages/ee/cli/eecli.py", line 17, in <module>
    from ee.cli import commands
  File "/usr/local/lib/python3.8/dist-packages/ee/cli/commands.py", line 34, in <module>
    import tensorflow.compat.v1 as tf
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 55, in <module>
    from ._api.v2 import compat
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/__init__.py", line 39, in <module>
    from . import v1
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 34, in <module>
    from . import compat
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 40, in <module>
    from . import v2
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/v1/compat/v2/__init__.py", line 32, in <module>
    from tensorflow._api.v2.compat.v2 import __internal__
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/v2/__init__.py", line 37, in <module>
    from . import compat
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/v2/compat/__init__.py", line 40, in <module>
    from . import v2
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/compat/v2/compat/v2/__init__.py", line 331, in <module>
    from tensorboard.summary._tf import summary
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/summary/__init__.py", line 22, in <module>
    from tensorboard.summary import v1  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/summary/v1.py", line 23, in <module>
    from tensorboard.plugins.histogram import summary as _histogram_summary
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/plugins/histogram/summary.py", line 35, in <module>
    from tensorboard.plugins.histogram import summary_v2
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/plugins/histogram/summary_v2.py", line 35, in <module>
    from tensorboard.util import tensor_util
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/util/tensor_util.py", line 20, in <module>
    from tensorboard.compat.tensorflow_stub import dtypes, compat, tensor_shape
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/compat/tensorflow_stub/__init__.py", line 22, in <module>
    from .dtypes import as_dtype  # noqa
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py", line 19, in <module>
    from . import pywrap_tensorflow
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/compat/tensorflow_stub/pywrap_tensorflow.py", line 22, in <module>
    from .io import gfile
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/compat/tensorflow_stub/io/__init__.py", line 17, in <module>
    from . import gfile  # noqa
  File "/usr/local/lib/python3.8/dist-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 40, in <module>
    import fsspec
  File "/home/sepal-user/.local/lib/python3.8/site-packages/fsspec/__init__.py", line 12, in <module>
    from .compression import available_compressions
  File "/home/sepal-user/.local/lib/python3.8/site-packages/fsspec/compression.py", line 149, in <module>
    register_compression("lz4", lz4.frame.open, "lz4")
AttributeError: module 'lz4.frame' has no attribute 'open'
```

Could you confirm you get something of the same type (meaining compatibility issues in the EE API dependencies) ?

@cdanielw Is there any chance that the OpenForis fork of earthengine get updated ? the current version on main is `1.276`

**Comment by dfguerrerom** [comment]
@12rambau I just tested and I do not have that error, it creates the link. However, when I paste it on browser, it says that the access is locked (below in Spanish): 

![image](https://user-images.githubusercontent.com/12363250/203119776-53701330-4283-400c-9f11-ce5a21ad2c25.png)

Could that relate to the deletion of my `.local`?

**Comment by 12rambau** [comment]
that's the one I get when I create a fresh env so no I think it's related to the fact our fork is deprecated

**Comment by cdanielw** [comment]
We have been running `v0.1.319` since August, and I've updated our fork to latest `v0.1.332`, so that can get deployed. There obviously have been changes on Google sides and `ee.Authenticate()` in `v.0.1.270` provides an incorrect URL. Using `v0.1.332` or newer solves this. Unfortunately, now `ee.Initialize()` breaks. We've finally reached the point where there been enough changes so authentication in our fork is broken. I'm investigating how to solve this.

**Comment by cdanielw** [comment]
I've updated the fork - this should work now. Let me know.

git+https://github.com/openforis/earthengine-api.git@v0.1.332#egg=earthengine-api&subdirectory=python

**Comment by 12rambau** [comment]
Is it already available on prod or only on test ?

**Comment by cdanielw** [comment]
It's not deployed to any server yet as the system library, but it doesn't have to be in order to use it inside a venv or as a user library.
